In [1]:
import pandas as pd
import numpy as np

### 1] Customers Dataset

#### *~ Loading Dataset ~*

In [2]:
customers = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_customers_dataset.csv")
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### *~ Dataset Overview ~*

In [3]:
print("=" * 50)
print("\t📊 CUSTOMER DATASET OVERVIEW")
print("=" * 50)

print("\n📌 Shape of the Dataset")
print(customers.shape)

print("\n📌 Total Customers")
print(customers.shape[0])

print("\n📌 Dataset Information")
customers.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(customers.columns)}")
print(customers.nunique())

==================================================
	📊 CUSTOMER DATASET OVERVIEW
==================================================

📌 Shape of the Dataset
(99441, 5)

📌 Total Customers
99441

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

📌 Unique Values in Each Column
Total Columns: 5
customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

### *~ Data Cleaning ~*

In [4]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING SUMMARY")
print("=" * 60)

# Missing Values
print("\n📌 Missing Values:")
print(customers.isnull().sum())

# Duplicate Records
print("\n📌 Duplicate Rows:")
print(customers.duplicated().sum())


print("\n✅ Data Cleaning Inspection Completed")

============================================================
		🧹 DATA CLEANING SUMMARY
============================================================

📌 Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

📌 Duplicate Rows:
0

✅ Data Cleaning Inspection Completed

## 2] Orders_Dataset

### *~ Loading Dataset ~*

In [5]:
import pandas as pd

orders = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

#### *~ Data Overview ~*

In [6]:
print("=" * 60)
print("\t\t📦 ORDERS DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(orders.shape)

print("\n📌 Total Orders")
print(orders.shape[0])

print("\n📌 Dataset Information")
orders.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(orders.columns)}")
print(orders.nunique())

============================================================
		📦 ORDERS DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(99441, 8)

📌 Total Orders
99441

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

📌 Unique Values in Each Column
Total Columns: 8
order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

In [7]:
print("=" * 60)
print("\t\t🔄 DATATYPE CONVERSION")
print("=" * 60)

date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

print("\n📌 Date Columns Converted Successfully")
print(date_cols)

print("\n📌 Updated Data Types")
print(orders[date_cols].dtypes)

============================================================
		🔄 DATATYPE CONVERSION
============================================================

📌 Date Columns Converted Successfully
['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

📌 Updated Data Types
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

#### *~ Data Cleaning ~*

In [8]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING REPORT")
print("=" * 60)

print(f"\n📊 Dataset Shape : {orders.shape}")

print("\n📌 Missing Values")
print("-" * 60)
print(orders.isnull().sum())

print("\n📌 Duplicate Records")
print("-" * 60)
print(f"Total Duplicate Rows : {orders.duplicated().sum()}")

print("\n📌 Data Type Validation")
print("-" * 60)
print(orders.dtypes)

============================================================
		🧹 DATA CLEANING REPORT
============================================================

📊 Dataset Shape : (99441, 8)

📌 Missing Values
------------------------------------------------------------
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

📌 Duplicate Records
------------------------------------------------------------
Total Duplicate Rows : 0

📌 Data Type Validation
------------------------------------------------------------
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [9]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values Before Cleaning")
print(orders.isnull().sum())

# Handle missing values
orders["order_approved_at"] = orders["order_approved_at"].fillna(
    orders["order_purchase_timestamp"]
)

orders["order_delivered_carrier_date"] = orders["order_delivered_carrier_date"].fillna(
    orders["order_approved_at"]
)

orders["order_delivered_customer_date"] = orders["order_delivered_customer_date"].fillna(
    orders["order_estimated_delivery_date"]
)

print("\n📌 Missing Values After Cleaning")
print(orders.isnull().sum())

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values Before Cleaning
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

📌 Missing Values After Cleaning
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

### 3] Order items

#### *~ Loading Dataset ~*

In [10]:
order_items = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_order_items_dataset.csv")
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

#### *~ Dataset Overview ~*

In [11]:
print("=" * 60)
print("\t\t📦 ORDER ITEMS DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(order_items.shape)

print("\n📌 Total Order Items")
print(order_items.shape[0])

print("\n📌 Dataset Information")
order_items.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(order_items.columns)}")
print(order_items.nunique())

============================================================
		📦 ORDER ITEMS DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(112650, 7)

📌 Total Order Items
112650

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB

📌 Unique Values in Each Column
Total Columns: 7
order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

In [12]:
print("=" * 60)
print("\t\t🔄 DATATYPE CONVERSION")
print("=" * 60)

order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"],
    errors="coerce"
)

print("\n📌 Updated Data Types")
print(order_items.dtypes)

============================================================
		🔄 DATATYPE CONVERSION
============================================================

📌 Updated Data Types
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

#### *~ Data Cleaning~*

In [13]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(order_items.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(order_items.duplicated().sum())

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
0

#### *~ Descriptive Statistics ~*

In [14]:
print("=" * 60)
print("\t\t📊 DESCRIPTIVE STATISTICS")
print("=" * 60)

print("\n📌 Price Statistics")
print("-" * 60)
print(order_items["price"].describe())

print("\n📌 Freight Value Statistics")
print("-" * 60)
print(order_items["freight_value"].describe())

============================================================
		📊 DESCRIPTIVE STATISTICS
============================================================

📌 Price Statistics
------------------------------------------------------------
count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

📌 Freight Value Statistics
------------------------------------------------------------
count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

### 4) Order Payments

#### *~ Loading Dataset ~*

In [15]:
order_payments = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_order_payments_dataset.csv")     
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

#### *~ Dataset Overview ~*

In [16]:
print("=" * 60)
print("\t💳 ORDER PAYMENTS DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(order_payments.shape)

print("\n📌 Total Payment Records")
print(order_payments.shape[0])

print("\n📌 Dataset Information")
order_payments.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(order_payments.columns)}")
print(order_payments.nunique())

============================================================
	💳 ORDER PAYMENTS DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(103886, 5)

📌 Total Payment Records
103886

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB

📌 Unique Values in Each Column
Total Columns: 5
order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

#### *~ Data Cleaning ~*

In [17]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(order_payments.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(order_payments.duplicated().sum())

print("\n📌 Dataset Shape After Cleaning")
print("-" * 60)
print(order_payments.shape)

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
0

📌 Dataset Shape After Cleaning
------------------------------------------------------------
(103886, 5)

#### *~ Descriptive Statistics ~*

In [18]:
print("=" * 60)
print("\t\t📊 DESCRIPTIVE STATISTICS")
print("=" * 60)

print("\n📌 Payment Value Statistics")
print("-" * 60)
print(order_payments["payment_value"].describe())

print("\n📌 Payment Installments Statistics")
print("-" * 60)
print(order_payments["payment_installments"].describe())

============================================================
		📊 DESCRIPTIVE STATISTICS
============================================================

📌 Payment Value Statistics
------------------------------------------------------------
count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

📌 Payment Installments Statistics
------------------------------------------------------------
count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

### 5) Order Reviews

#### *~ Loading Dataset ~*

In [19]:
order_reviews = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_order_reviews_dataset.csv")
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

#### *~ Data Overview ~*

In [20]:
print("=" * 60)
print("\t\t⭐ ORDER REVIEWS DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(order_reviews.shape)

print("\n📌 Total Reviews")
print(order_reviews.shape[0])

print("\n📌 Dataset Information")
order_reviews.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(order_reviews.columns)}")
print(order_reviews.nunique())

print("\n📌 Date Columns")
date_cols = [
    "review_creation_date",
    "review_answer_timestamp"
]
print(date_cols)

============================================================
		⭐ ORDER REVIEWS DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(99224, 7)

📌 Total Reviews
99224

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB

📌 Unique Values in Each Column
Total Columns: 7
review_id                  98410
order_id                   98673
review_score                   5
review_comment_title        4527
review_comment_message     36159
review_creation_date         636
review_answer_timestamp    98248
dtype: int64

📌 Date Columns
['review_creation_date', 'review_answer_timestamp']

In [21]:
print("=" * 60)
print("\t\t🔄 DATATYPE CONVERSION")
print("=" * 60)

date_cols = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_cols:
    order_reviews[col] = pd.to_datetime(
        order_reviews[col],
        errors="coerce"
    )

print("\n📌 Updated Data Types")
print(order_reviews[date_cols].dtypes)

============================================================
		🔄 DATATYPE CONVERSION
============================================================

📌 Updated Data Types
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

#### *~ Data Cleaning ~*

In [22]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(order_reviews.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(order_reviews.duplicated().sum())

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
0

In [23]:
print("=" * 60)
print("\t\t🧹 REVIEW TEXT CLEANING")
print("=" * 60)

print("\n📌 Handling Missing Review Titles and Comments")
print("-" * 60)

# Fill missing review titles
order_reviews["review_comment_title"] = (
    order_reviews["review_comment_title"]
    .fillna("No Review Title")
)

# Fill missing review messages
order_reviews["review_comment_message"] = (
    order_reviews["review_comment_message"]
    .fillna("No Review Comment")
)

print("✅ Missing review titles replaced with 'No Review Title'")
print("✅ Missing review comments replaced with 'No Review Comment'")

print("\n📌 Missing Values After Cleaning")
print("-" * 60)
print(
    order_reviews[
        ["review_comment_title", "review_comment_message"]
    ].isnull().sum()
)

============================================================
		🧹 REVIEW TEXT CLEANING
============================================================

📌 Handling Missing Review Titles and Comments
------------------------------------------------------------
✅ Missing review titles replaced with 'No Review Title'
✅ Missing review comments replaced with 'No Review Comment'

📌 Missing Values After Cleaning
------------------------------------------------------------
review_comment_title      0
review_comment_message    0
dtype: int64

#### *~ Descriptive Statistics ~*

In [24]:
print("=" * 60)
print("\t\t📊 DESCRIPTIVE STATISTICS")
print("=" * 60)

print("\n📌 Review Score Statistics")
print("-" * 60)
print(order_reviews["review_score"].describe())

============================================================
		📊 DESCRIPTIVE STATISTICS
============================================================

📌 Review Score Statistics
------------------------------------------------------------
count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

### 6) Products

#### *~ Loading Dataset ~*

In [25]:
products = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_products_dataset.csv")
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

#### *~ Dataset Overview ~*

In [26]:
print("=" * 60)
print("\t\t📦 PRODUCTS DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(products.shape)

print("\n📌 Total Products")
print(products.shape[0])

print("\n📌 Dataset Information")
products.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(products.columns)}")
print(products.nunique())

============================================================
		📦 PRODUCTS DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(32951, 9)

📌 Total Products
32951

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB

📌 Unique Values in Each Column
Total Columns: 9
product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

#### *~ Data Cleaning ~*

In [27]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(products.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(products.duplicated().sum())

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
0

In [28]:
print("=" * 60)
print("\t\t🔧 MISSING VALUE TREATMENT")
print("=" * 60)

print("\n📌 Missing Values Before Cleaning")
print("-" * 60)
print(products.isnull().sum())

# Fill missing category names
products["product_category_name"] = (
    products["product_category_name"]
    .fillna("Unknown Category")
)

# Fill missing product name length
products["product_name_lenght"] = (
    products["product_name_lenght"]
    .fillna(products["product_name_lenght"].median())
)

# Fill missing product description length
products["product_description_lenght"] = (
    products["product_description_lenght"]
    .fillna(products["product_description_lenght"].median())
)

# Fill missing photo quantity
products["product_photos_qty"] = (
    products["product_photos_qty"]
    .fillna(products["product_photos_qty"].median())
)

print("\n📌 Missing Values After Cleaning")
print("-" * 60)
print(products.isnull().sum())

============================================================
		🔧 MISSING VALUE TREATMENT
============================================================

📌 Missing Values Before Cleaning
------------------------------------------------------------
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

📌 Missing Values After Cleaning
------------------------------------------------------------
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              2
product_length_cm             2
product_height_cm             2
product_width_cm              2
dtype: int64

#### *~ Descriptive Statistics ~*

In [29]:
print("=" * 80)
print("\t\t\t📊 DESCRIPTIVE STATISTICS")
print("=" * 80)

print(products.describe())

================================================================================
			📊 DESCRIPTIVE STATISTICS
================================================================================
       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32951.000000                32951.000000        32951.000000
mean             48.523656                  768.227945            2.166975
std              10.156155                  629.658469            1.728063
min               5.000000                    4.000000            1.000000
25%              42.000000                  344.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  961.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000

### 7) Product Category Name Translation

#### *~ Loading Dataset ~*

In [30]:
category_translation = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\product_category_name_translation.csv")   
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

#### *~ Dataset Overview ~*

In [31]:
print("=" * 60)
print("\t🌐 PRODUCT CATEGORY TRANSLATION OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(category_translation.shape)

print("\n📌 Total Category Mappings")
print(category_translation.shape[0])

print("\n📌 Dataset Information")
category_translation.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(category_translation.columns)}")
print(category_translation.nunique())

============================================================
	🌐 PRODUCT CATEGORY TRANSLATION OVERVIEW
============================================================

📌 Shape of the Dataset
(71, 2)

📌 Total Category Mappings
71

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 3.5 KB

📌 Unique Values in Each Column
Total Columns: 2
product_category_name            71
product_category_name_english    71
dtype: int64

#### *~ Data Cleaning ~*

In [32]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(category_translation.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(category_translation.duplicated().sum())

print("\n📌 Dataset Shape After Cleaning")
print("-" * 60)
print(category_translation.shape)

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
product_category_name            0
product_category_name_english    0
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
0

📌 Dataset Shape After Cleaning
------------------------------------------------------------
(71, 2)

### 8) Sellers

#### *~ Loading Dataset ~*

In [33]:
sellers = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_sellers_dataset.csv")
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

#### *~ Dataset Overview ~*

In [34]:
print("=" * 60)
print("\t\t🏪 SELLERS DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(sellers.shape)

print("\n📌 Total Sellers")
print(sellers.shape[0])

print("\n📌 Dataset Information")
sellers.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(sellers.columns)}")
print(sellers.nunique())

============================================================
		🏪 SELLERS DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(3095, 4)

📌 Total Sellers
3095

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 230.3 KB

📌 Unique Values in Each Column
Total Columns: 4
seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

#### *~ Data Cleaning ~*

In [35]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(sellers.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(sellers.duplicated().sum())

print("\n📌 Dataset Shape After Cleaning")
print("-" * 60)
print(sellers.shape)

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
0

📌 Dataset Shape After Cleaning
------------------------------------------------------------
(3095, 4)

### 9) Geolocation

#### *~ Loading dataset ~*

In [36]:
geolocation = pd.read_csv(r"C:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\01_Data\Raw\olist_geolocation_dataset.csv")
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

#### *~ Dataset Overview ~*

In [37]:
print("=" * 60)
print("\t\t🌍 GEOLOCATION DATASET OVERVIEW")
print("=" * 60)

print("\n📌 Shape of the Dataset")
print(geolocation.shape)

print("\n📌 Total Location Records")
print(geolocation.shape[0])

print("\n📌 Dataset Information")
geolocation.info()

print("\n📌 Unique Values in Each Column")
print(f"Total Columns: {len(geolocation.columns)}")
print(geolocation.nunique())

============================================================
		🌍 GEOLOCATION DATASET OVERVIEW
============================================================

📌 Shape of the Dataset
(1000163, 5)

📌 Total Location Records
1000163

📌 Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB

📌 Unique Values in Each Column
Total Columns: 5
geolocation_zip_code_prefix     19015
geolocation_lat                717360
geolocation_lng                717613
geolocation_city                 8011
geolocation_state                  27
dtype: int64

#### *~ Data Cleaning ~*

In [38]:
print("=" * 60)
print("\t\t🧹 DATA CLEANING")
print("=" * 60)

print("\n📌 Missing Values")
print("-" * 60)
print(geolocation.isnull().sum())

print("\n📌 Duplicate Rows")
print("-" * 60)
print(geolocation.duplicated().sum())

print("\n📌 Dataset Shape After Cleaning")
print("-" * 60)
print(geolocation.shape)

============================================================
		🧹 DATA CLEANING
============================================================

📌 Missing Values
------------------------------------------------------------
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

📌 Duplicate Rows
------------------------------------------------------------
261831

📌 Dataset Shape After Cleaning
------------------------------------------------------------
(1000163, 5)

#### *~ Descriptive Statistics ~*

In [39]:
print("=" * 60)
print("\t\t📊 DESCRIPTIVE STATISTICS")
print("=" * 60)

print(
    geolocation[
        ["geolocation_lat", "geolocation_lng"]
    ].describe()
)

============================================================
		📊 DESCRIPTIVE STATISTICS
============================================================
       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

In [40]:
import os
import pandas as pd

# Make sure we're at project root
if "notebooks" in os.getcwd():
    os.chdir("..")

print("Working directory:", os.getcwd())

# Load raw files
orders = pd.read_csv("data/olist_orders_dataset.csv")
order_items = pd.read_csv("data/olist_order_items_dataset.csv")
customers = pd.read_csv("data/olist_customers_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
payments = pd.read_csv("data/olist_order_payments_dataset.csv")
reviews = pd.read_csv("data/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("data/olist_sellers_dataset.csv")
category_translation = pd.read_csv("data/product_category_name_translation.csv")


# Create cleaned folder and save
os.makedirs("data/cleaned", exist_ok=True)

orders.to_csv("data/cleaned/orders_clean.csv", index=False)
order_items.to_csv("data/cleaned/order_items_clean.csv", index=False)
customers.to_csv("data/cleaned/customers_clean.csv", index=False)
products.to_csv("data/cleaned/products_clean.csv", index=False)
payments.to_csv("data/cleaned/payments_clean.csv", index=False)
reviews.to_csv("data/cleaned/reviews_clean.csv", index=False)
sellers.to_csv("data/cleaned/sellers_clean.csv", index=False)
category_translation.to_csv("data/cleaned/category_translation_clean.csv", index=False)

# Verify
saved = os.listdir("data/cleaned")
print(f"\n{len(saved)} files saved to data/cleaned/:")
for f in saved:
    print(" ✓", f)

Working directory: c:\Users\HOLE\DATA ANALYST\RetailPulseAI - Project\02_Notebooks

FileNotFoundError: [Errno 2] No such file or directory: 'data/olist_orders_dataset.csv'